#[derive(Debug)]
#[allow(dead_code)]
#[derive(PartialEq)]
pub enum ICMPType {
    DestinationUnreachable = 1,
    PacketTooBig = 2,
    TimeExceeded = 3,
    ParameterProblem = 4,
    EchoRequest = 128,
    EchoReply = 129,
    MulticastListenerQuery = 130,
    MulticastListenerReport = 131,
    MulticastListenerDone = 132,
    RouterSolicitation = 133,
    RouterAdvertisement = 134,
    NeighborSolicitation = 135,
    NeighborAdvertisement = 136,
    RedirectMessage = 137,
    RouterRenumbering = 138,
    ICMPNodeInformationQuery = 139,
    ICMPNodeInformationResponse = 140,
    InverseNeighborDiscoverySolicitationMessage = 141,
    InverseNeighborDiscoveryAdvertisementMessage = 142,
    Version2MulticastListenerReport = 143,
    HomeAgentAddressDiscoveryRequestMessage = 144,
    HomeAgentAddressDiscoveryReplyMessage = 145,
    MobilePrefixSolicitation = 146,
    MobilePrefixAdvertisement = 147,
    CertificationPathSolicitationMessage = 148,
    CertificationPathAdvertisementMessage = 149,
    MulticastRouterAdvertisement = 151,
    MulticastRouterSolicitation = 152,
    MulticastRouterTermination = 153,
    FMIPv6Messages = 154,
    RPLControlMessage = 155,
    ILNPv6LocatorUpdateMessage = 156,
    DuplicateAddressRequest = 157,
    DuplicateAddressConfirmation = 158,
    MPLControlMessage = 159,
    ExtendedEchoRequest = 160,
    ExtendedEchoReply = 161,
}

pub fn to_icmp_type(code: u8) -> Option<ICMPType> {
    match code {
        1 => Some(ICMPType::DestinationUnreachable),
        2 => Some(ICMPType::PacketTooBig),
        3 => Some(ICMPType::TimeExceeded),
        4 => Some(ICMPType::ParameterProblem),
        128 => Some(ICMPType::EchoRequest),
        129 => Some(ICMPType::EchoReply),
        130 => Some(ICMPType::MulticastListenerQuery),
        131 => Some(ICMPType::MulticastListenerReport),
        132 => Some(ICMPType::MulticastListenerDone),
        133 => Some(ICMPType::RouterSolicitation),
        134 => Some(ICMPType::RouterAdvertisement),
        135 => Some(ICMPType::NeighborSolicitation),
        136 => Some(ICMPType::NeighborAdvertisement),
        137 => Some(ICMPType::RedirectMessage),
        138 => Some(ICMPType::RouterRenumbering),
        139 => Some(ICMPType::ICMPNodeInformationQuery),
        140 => Some(ICMPType::ICMPNodeInformationResponse),
        141 => Some(ICMPType::InverseNeighborDiscoverySolicitationMessage),
        142 => Some(ICMPType::InverseNeighborDiscoveryAdvertisementMessage),
        143 => Some(ICMPType::Version2MulticastListenerReport),
        144 => Some(ICMPType::HomeAgentAddressDiscoveryRequestMessage),
        145 => Some(ICMPType::HomeAgentAddressDiscoveryReplyMessage),
        146 => Some(ICMPType::MobilePrefixSolicitation),
        147 => Some(ICMPType::MobilePrefixAdvertisement),
        148 => Some(ICMPType::CertificationPathSolicitationMessage),
        149 => Some(ICMPType::CertificationPathAdvertisementMessage),
        151 => Some(ICMPType::MulticastRouterAdvertisement),
        152 => Some(ICMPType::MulticastRouterSolicitation),
        153 => Some(ICMPType::MulticastRouterTermination),
        154 => Some(ICMPType::FMIPv6Messages),
        155 => Some(ICMPType::RPLControlMessage),
        156 => Some(ICMPType::ILNPv6LocatorUpdateMessage),
        157 => Some(ICMPType::DuplicateAddressRequest),
        158 => Some(ICMPType::DuplicateAddressConfirmation),
        159 => Some(ICMPType::MPLControlMessage),
        160 => Some(ICMPType::ExtendedEchoRequest),
        161 => Some(ICMPType::ExtendedEchoReply),
        _ => None,
    }
}
